version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    networks:
      - my_network

networks:
  my_network:
    driver: overlay

